# Generated by Django 5.2.1 on 2025-06-19 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_mother_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
    ]
