# Generated by Django 5.2.1 on 2025-06-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_student_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Blog Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
    ]
