# Generated by Django 4.2.11 on 2025-07-09 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model_name', models.CharField(max_length=100)),
                ('car_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carcompany')),
            ],
        ),
    ]
